[workspace]
authors = ["Simone Massaro <simone.massaro@mone27.net>"]
channels = ["conda-forge"]
name = "pandion_logo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
export = "python export_logos.py"

[dependencies]
cairosvg = ">=2.8.2,<3"
lxml = ">=5.4.0,<6"
pyprojroot = ">=0.3.0,<0.4"
